import type { GenerationTask } from './types'

const now = Date.now()

export const seedTasks: GenerationTask[] = [
  {
    id: 'task-1',
    type: 'image',
    prompt: 'Neon cyberpunk city under rain, cinematic lighting, 8k',
    model: 'Midjourney v6',
    status: 'running',
    progress: 64,
    createdAt: now - 120_000,
    etaSeconds: 30,
    durationMs: 45_000,
    credits: 80,
  },
  {
    id: 'task-2',
    type: 'video',
    prompt: 'Slow motion ocean waves at sunset, drone shot',
    model: 'Runway Gen-3',
    status: 'running',
    progress: 28,
    createdAt: now - 90_000,
    etaSeconds: 120,
    durationMs: 180_000,
    credits: 150,
  },
  {
    id: 'task-3',
    type: 'text',
    prompt: 'Write a product description for an AI aggregator platform',
    model: 'GPT-4o',
    status: 'queued',
    progress: 0,
    createdAt: now - 60_000,
    etaSeconds: 15,
    durationMs: 20_000,
    credits: 10,
    queuePosition: 1,
  },
  {
    id: 'task-4',
    type: 'audio',
    prompt: 'Ambient lo-fi beat with soft piano, 90 BPM',
    model: 'Suno v3',
    status: 'queued',
    progress: 0,
    createdAt: now - 45_000,
    etaSeconds: 60,
    durationMs: 90_000,
    credits: 40,
    queuePosition: 2,
  },
  {
    id: 'task-5',
    type: 'image',
    prompt: 'Minimalist logo for tech startup, flat design',
    model: 'DALL·E 3',
    status: 'queued',
    progress: 0,
    createdAt: now - 30_000,
    etaSeconds: 25,
    durationMs: 35_000,
    credits: 50,
    queuePosition: 3,
  },
  {
    id: 'task-6',
    type: 'text',
    prompt: 'Summarize quarterly report into 5 bullet points',
    model: 'Claude 3.5',
    status: 'done',
    progress: 100,
    createdAt: now - 600_000,
    etaSeconds: 0,
    durationMs: 18_000,
    credits: 8,
  },
  {
    id: 'task-7',
    type: 'image',
    prompt: 'Portrait of a cat astronaut in space suit',
    model: 'Stable Diffusion XL',
    status: 'done',
    progress: 100,
    createdAt: now - 900_000,
    etaSeconds: 0,
    durationMs: 40_000,
    credits: 35,
  },
  {
    id: 'task-8',
    type: 'video',
    prompt: 'Product demo animation, 15 seconds, white background',
    model: 'Pika 1.5',
    status: 'failed',
    progress: 42,
    createdAt: now - 300_000,
    etaSeconds: 0,
    durationMs: 120_000,
    credits: 100,
    error: 'Недостаточно кредитов',
  },
  {
    id: 'task-9',
    type: 'audio',
    prompt: 'Voiceover for podcast intro, warm male voice',
    model: 'ElevenLabs',
    status: 'failed',
    progress: 18,
    createdAt: now - 240_000,
    etaSeconds: 0,
    durationMs: 60_000,
    credits: 25,
    error: 'Модель временно недоступна',
  },
  {
    id: 'task-10',
    type: 'text',
    prompt: 'Translate landing page copy to English',
    model: 'GPT-4o mini',
    status: 'canceled',
    progress: 0,
    createdAt: now - 180_000,
    etaSeconds: 0,
    durationMs: 15_000,
    credits: 5,
  },
]
